name: Estadisticas tradicionales Euroleague y Eurocup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * TUE-SAT' 

jobs:
  Get-Estadisticas-tradicionales-Euroleague:
    name: Actualizar tradicionales Euroleague y Eurocup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
          r-version: 'release'
          
      - name: Install libcurl and libssl on Linux
        run: sudo apt-get -y install libcurl4-openssl-dev 
        shell: bash
        
      - name: Cache CRAN packages
        uses: actions/cache@v3 
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
          
      - name: Install CRAN packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: httr, purrr, tidyr, dplyr, tibble, jsonlite
          
      - name: Run R script
        env:
          JSON_STATS_EUROLEAGUE: ${{ secrets.JSON_STATS_EUROLEAGUE }}
          JSON_STATS_EUROCUP: ${{ secrets.JSON_STATS_EUROCUP }}
        run: Rscript main.R
        shell: bash

      - name: Commit changes in data folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/*.csv
          git diff --cached --quiet || git commit -m "Auto-update: Euroleague traditional Stats"
        shell: bash

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
